services:
  giocci:
    image: ghcr.io/biyooon-ex/giocci_platform/giocci:0.3.0
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./config/giocci.exs:/app/giocci.exs:ro
      - ./config/DEFAULT_CONFIG.json5:/app/zenoh.json:ro
    restart: "always"
    stdin_open: true
    tty: true
