services:
  giocci:
    image: ghcr.io/biyooon-ex/giocci_platform/giocci:0.3.1-rc.0
    build:
      context: ./
      dockerfile: ./Dockerfile
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    volumes:
      - ./config/giocci.exs:/app/giocci.exs:ro
      - ./config/zenoh.json5:/app/zenoh.json5:ro
    restart: "always"
    stdin_open: true
    tty: true
