services:
  zenohd:
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
    image: ghcr.io/biyooon-ex/giocci_platform/zenohd:1.7.2
    volumes:
      - .:/app
    ports:
      - "7447:7447"
      - "7446:7446/udp"
